#include "ps2recomp/toml_generator.h"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <vector>

namespace fs = std::filesystem;

namespace ps2recomp
{
    bool TomlGenerator::generate(const TomlGeneratorInput &input, const std::string &outputPath)
    {
        std::ofstream file(outputPath);
        if (!file)
        {
            std::cerr << "Failed to open output file: " << outputPath << std::endl;
            return false;
        }

        fs::path elfPathObj(input.elfPath);
        std::string elfFileName = elfPathObj.filename().string();

        fs::path outputPathObj(outputPath);
        fs::path outputDir = outputPathObj.parent_path();
        if (outputDir.empty())
        {
            outputDir = ".";
        }

        const fs::path generatedOutputDir = outputDir / "output";
        std::string outputDirStr = generatedOutputDir.generic_string() + "/";

        if (!fs::exists(generatedOutputDir))
        {
            fs::create_directories(generatedOutputDir);
        }

        file << "# PS2Recomp configuration for: " << elfFileName << "\n";
        file << "# Generated by ElfAnalyzer\n\n";

        file << "[general]\n";
        file << "# Path to input ELF file\n";
        file << "input = \"" << escapeBackslashes(input.elfPath) << "\"\n\n";

        file << "# Path to Ghidra exported function map (optional CSV)\n";
        file << "ghidra_output = \"\"\n\n";

        file << "# Path to output directory\n";
        file << "output = \"" << escapeBackslashes(outputDirStr) << "\"\n\n";

        file << "# Single file output mode (recommended for large games)\n";
        file << "single_file_output = false\n\n";

        file << "# Patch policy (instruction-driven handling is preferred for syscalls)\n";
        file << "patch_syscalls = false\n";
        file << "patch_cop0 = true\n";
        file << "patch_cache = true\n\n";

        std::unordered_map<std::string, size_t> functionNameCounts;
        functionNameCounts.reserve(input.context.functions.size());
        for (const auto &func : input.context.functions)
        {
            if (!func.name.empty())
            {
                functionNameCounts[func.name]++;
            }
        }

        auto makeSelector = [&](const std::string &name, uint32_t start) -> std::string
        {
            std::stringstream selector;
            selector << name << "@0x"
                     << std::hex << std::uppercase << std::setw(8) << std::setfill('0')
                     << start;
            return selector.str();
        };

        auto collectFunctionSelectors =
            [&](const std::unordered_set<std::string> &nameSet) -> std::vector<std::string>
        {
            std::vector<const Function *> orderedFunctions;
            orderedFunctions.reserve(input.context.functions.size());
            for (const auto &func : input.context.functions)
            {
                orderedFunctions.push_back(&func);
            }

            std::sort(orderedFunctions.begin(), orderedFunctions.end(),
                      [](const Function *a, const Function *b)
                      { return a->start < b->start; });

            std::vector<std::string> entries;
            std::unordered_set<std::string> seenEntries;
            std::unordered_set<std::string> coveredNames;

            for (const Function *func : orderedFunctions)
            {
                if (!nameSet.contains(func->name))
                {
                    continue;
                }

                coveredNames.insert(func->name);
                const std::string entry = makeSelector(func->name, func->start);
                if (seenEntries.insert(entry).second)
                {
                    entries.push_back(entry);
                }
            }

            std::vector<std::string> leftovers;
            leftovers.reserve(nameSet.size());
            for (const auto &name : nameSet)
            {
                if (!coveredNames.contains(name) && seenEntries.insert(name).second)
                {
                    leftovers.push_back(name);
                }
            }
            std::sort(leftovers.begin(), leftovers.end());
            entries.insert(entries.end(), leftovers.begin(), leftovers.end());

            return entries;
        };

        const std::vector<std::string> stubEntries = collectFunctionSelectors(input.libFunctions);
        const std::vector<std::string> untrackedStubEntries = collectFunctionSelectors(input.untrackedStubFunctions);

        file << "# Functions to stub (only names with runtime syscall/stub handlers)\n";
        file << "stubs = [\n";
        for (const auto &func : stubEntries)
        {
            file << "  \"" << func << "\",\n";
        }
        file << "]\n\n";

        file << "# Guest functions without runtime handlers that may be referenced by address.\n";
        file << "# PS2Recomp keeps their guest implementation and exposes exact callable entries.\n";
        file << "entry_points = [\n";
        for (const auto &func : untrackedStubEntries)
        {
            file << "  \"" << func << "\",\n";
        }
        file << "]\n\n";

        file << "# Legacy compatibility field. The analyzer no longer auto-populates skip entries.\n";
        file << "skip = []\n\n";

        if (!input.mmioByInstructionAddress.empty())
        {
            file << "# Detected MMIO accesses\n";
            file << "[mmio]\n";
            for (const auto &[instAddr, mmioAddr] : input.mmioByInstructionAddress)
            {
                file << "\"0x" << std::hex << instAddr << "\" = \"0x" << mmioAddr << "\"\n"
                     << std::dec;
            }
            file << "\n";
        }

        if (!input.jumpTables.empty())
        {
            file << "# Jump tables detected in the program\n";
            file << "[jump_tables]\n";

            for (const auto &jt : input.jumpTables)
            {
                file << "[[jump_tables.table]]\n";
                file << "address = \"0x" << std::hex << jt.address << "\"\n"
                     << std::dec;
                file << "entries = [\n";

                for (const auto &[index, target] : jt.entries)
                {
                    file << "  { index = " << index << ", target = \"0x"
                         << std::hex << target << "\" },\n"
                         << std::dec;
                }

                file << "]\n\n";
            }
        }

        if (!input.patches.empty())
        {
            file << "# Patches to apply during recompilation\n";
            file << "[patches]\n";
            file << "# Individual instruction patches\n";
            file << "instructions = [\n";
            for (const auto &[address, value] : input.patches)
            {
                auto reasonIt = input.patchReasons.find(address);
                const std::string reason = reasonIt == input.patchReasons.end() ? "" : reasonIt->second;
                file << "  { address = \"0x" << std::hex << address << "\", value = \"0x"
                     << std::hex << value << "\" },  # " << reason << "\n";
            }
            file << "]\n\n";
        }

        file << "# Performance critical functions (may need manual optimization)\n";
        file << "[performance]\n";
        file << "critical = [\n";
        for (const auto &func : input.context.functions)
        {
            auto reasonIt = input.performanceCriticalReasons.find(func.start);
            if (reasonIt != input.performanceCriticalReasons.end())
            {
                file << "  \"" << func.name << "\", # " << reasonIt->second << "\n";
            }
        }
        file << "]\n\n";

        std::cout << "Generated TOML configuration: " << outputPath << std::endl;
        return true;
    }

    std::string TomlGenerator::escapeBackslashes(const std::string &path)
    {
        std::string result;
        for (char ch : path)
        {
            if (ch == '\\')
            {
                result.append("\\\\");
            }
            else
            {
                result.push_back(ch);
            }
        }
        return result;
    }
}
